# Generated by Django 3.2 on 2021-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='class_records/images')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='class_records/images')),
            ],
        ),
    ]
