# Generated by Django 3.2 on 2021-04-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_records', '0002_auto_20210411_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
